# Generated by Django 5.2.15 on 2026-07-11 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('root', models.CharField(help_text='스캔 루트(VPS 파일시스템 경로)', max_length=400)),
                ('skips', models.JSONField(blank=True, default=list, help_text='기본 제외 외 추가 제외(상대 경로 접두)')),
                ('stages', models.JSONField(blank=True, default=list, help_text='논리층 열 이름(비면 기본 축)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ConceptEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.SlugField()),
                ('t', models.SlugField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('both', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_edges', to='graph.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('stats', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='graph.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.SlugField()),
                ('name', models.CharField(max_length=120)),
                ('one', models.CharField(blank=True, max_length=300)),
                ('src', models.CharField(blank=True, max_length=200)),
                ('stage', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('globs', models.JSONField(blank=True, default=list)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='graph.project')),
            ],
            options={
                'ordering': ['stage', 'order', 'cid'],
                'unique_together': {('project', 'cid')},
            },
        ),
    ]
