# Generated by Django 5.2.15 on 2026-07-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('root', models.CharField(help_text='스캔 루트(VPS 파일시스템 경로)', max_length=400)),
                ('skips', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('stats', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='graph.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=420)),
                ('type', models.CharField(db_index=True, default='concept', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(db_index=True, default='user', max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='graph.project')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('project', 'nid')},
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(max_length=420)),
                ('t', models.CharField(max_length=420)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('both', models.BooleanField(default=False)),
                ('origin', models.CharField(db_index=True, default='user', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='graph.project')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['project', 's'], name='graph_edge_project_a2755b_idx'), models.Index(fields=['project', 't'], name='graph_edge_project_51f3d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.SlugField()),
                ('name', models.CharField(max_length=80)),
                ('types', models.JSONField(blank=True, default=list)),
                ('lanes', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='graph.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'vid')},
            },
        ),
    ]
