# Generated by Django 5.2.15 on 2026-07-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.SlugField()),
                ('name', models.CharField(default='캔버스', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvases', to='graph.project')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('project', 'cid')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='sticky', max_length=16)),
                ('text', models.TextField(blank=True)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('w', models.FloatField(default=180)),
                ('h', models.FloatField(default=100)),
                ('origin', models.CharField(db_index=True, default='user', max_length=10)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('z', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='graph.canvas')),
            ],
            options={
                'ordering': ['z', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('origin', models.CharField(default='user', max_length=10)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='graph.canvas')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_links', to='graph.item')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_links', to='graph.item')),
            ],
        ),
    ]
