# Generated by Django 5.2.15 on 2026-07-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(db_index=True, default='murmur', help_text='피드백이 달린 서비스 슬러그(멀티서비스 확장)', max_length=30)),
                ('route', models.CharField(help_text='페이지 경로(/channels/U-001)', max_length=300)),
                ('selector', models.TextField(blank=True, help_text='핀 부착 CSS 선택자(프론트가 생성·복원)')),
                ('element_label', models.CharField(blank=True, help_text="요소 설명(버튼 '보내기' 등)", max_length=120)),
                ('anchor_text', models.CharField(blank=True, help_text='요소 텍스트 스냅샷 — 셀렉터가 깨져도 식별', max_length=160)),
                ('pos_x', models.FloatField(default=50, help_text='요소 내 상대 X(%)')),
                ('pos_y', models.FloatField(default=50, help_text='요소 내 상대 Y(%)')),
                ('body', models.TextField(help_text='피드백 본문')),
                ('author_handle', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('open', '대기'), ('resolved', '처리됨'), ('confirmed', '확인됨')], db_index=True, default='open', max_length=10)),
                ('resolution', models.TextField(blank=True, help_text='처리 노트(무엇을 어떻게 고쳤나·커밋)')),
                ('resolved_by', models.CharField(blank=True, help_text='처리 주체(AI 세션 등)', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', 'status'], name='feedback_fe_service_7bf675_idx'), models.Index(fields=['service', 'route'], name='feedback_fe_service_489ebc_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_handle', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedbackitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
